name: melos_example
environment:
  sdk: ^3.11.5

workspace:
  - packages/*

dev_dependencies:
  melos: ^7.0.0

melos:
  ide:
    intellij:
      enabled: false
  sdkPath: .fvm/flutter_sdk
  command:
    bootstrap:
      runPubGetInParallel: true
      hooks:
        post: |
          melos exec --depends-on="build_runner" -- "dart run build_runner build --delete-conflicting-outputs"