name: melos_example
environment:
  sdk: ^3.11.5

workspace:
  - packages/*

dev_dependencies:
  melos: ^7.0.0

melos:
  ide:
    intellij:
      enabled: false
  sdkPath: .fvm/flutter_sdk
  command:
    bootstrap:
      runPubGetInParallel: true
      hooks:
        post: |
          melos exec --depends-on="build_runner" -- "dart run build_runner build --delete-conflicting-outputs"
  scripts:
    test:smart:
      run: melos exec --fail-fast --dir-exists="test" --diff=main --include-dependents -- "dart test"
      description: "It runs tests only for packages that have changed relative to the main branch and depend on it."